services:
  # Frontend Service (Next.js)
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      args:
        - NEXT_PUBLIC_API_URL=/api
    container_name: yttmp3_frontend
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=/api
      - USE_YTDLP_CONTAINER=1
    volumes:
      - ./logs/frontend:/app/logs
      - yttmp3_tmp:/tmp
    networks:
      - yttmp3_network

  # no dependencies; API is served by Next.js

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: yttmp3_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
      - ./ssl-challenge:/var/www/certbot:ro
      - ./logs/nginx:/var/log/nginx
    networks:
      - yttmp3_network
    depends_on:
      - frontend

  # Dedicated yt-dlp worker container using official image
  ytdlp:
    image: tnk4on/yt-dlp:latest
    container_name: yttmp3_ytdlp
    restart: unless-stopped
    entrypoint: ""
    command: ["sleep", "infinity"]
    volumes:
      - yttmp3_tmp:/media
    networks:
      - yttmp3_network

  # Certbot for SSL certificates
  certbot:
    image: certbot/certbot
    container_name: yttmp3_certbot
    volumes:
      - ./ssl:/etc/letsencrypt
      - ./ssl-challenge:/var/www/certbot
    command: certonly --webroot --webroot-path=/var/www/certbot --email bilaltoor786786@gmail.com --agree-tos --no-eff-email -d yttmp3.com -d www.yttmp3.com
    networks:
      - yttmp3_network

networks:
  yttmp3_network:
    driver: bridge

volumes:
  yttmp3_tmp:
