services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend.local
    container_name: yttmp3_backend_local
    environment:
      - FLASK_ENV=production
      - PYTHONPATH=/app
    ports:
      - "5000:5000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 20s
      timeout: 5s
      retries: 3
      start_period: 20s

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend.local
    container_name: yttmp3_frontend_local
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost:5000/api
    ports:
      - "3000:3000"
    depends_on:
      backend:
        condition: service_healthy

networks:
  default:
    driver: bridge
